### ISSUE TITLE
How do you handle non-reversible migrations?

### ISSUE THREAD

**Issue by YoshiWalsh** [Kauto/better-sqlite3-helper#10]
Hi,

There are sometimes cases where we need to run a migration that cannot be reversed, or is difficult to reverse. For example, take the following migration:

```sql
-- Up
ALTER TABLE files ADD COLUMN size INTEGER;
```

Because SQLite does not support removing columns, reversing this is very difficult:

```sql
-- Down
PRAGMA foreign_keys=off;
DROP INDEX `file_path_idx`;
ALTER TABLE files RENAME TO files_old;
CREATE TABLE `files` (
    id INTEGER PRIMARY KEY,
    libraryId INTEGER NOT NULL,
    path STRING NOT NULL, -- Relative to the library path
    lastModified INTEGER NOT NULL,
    itemId INTEGER NOT NULL,
    stillExists INTEGER NOT NULL, -- Indicates whether this file was present during the last scan
    UNIQUE(libraryId, path),
    FOREIGN KEY(libraryId) REFERENCES libraries(id),
    FOREIGN KEY(itemId) REFERENCES items(id)
);
CREATE INDEX `file_path_idx` ON files(path);
INSERT INTO `files` (id, libraryId, path, lastModified, itemId, stillExists)
    SELECT id, libraryId, path, lastModified, itemId, stillExists FROM files_old;
DROP TABLE files_old;
PRAGMA foreign_keys=on;
```

It'd be nice if it were possible to make one-way migrations by omitting the `-- Down` section.

**Comment by Kauto** [comment]
Hi,

you can't leave a down empty. However, if you only write a comment in the down you can skip the reversing:

```sql
-- Up
SELECT (1*1)

-- Down
-- no Down needed --
```

**Comment by YoshiWalsh** [comment]
If you do that, won't it run the Up again next time? So if you're trying to create a column or table but it already exists you'd get an error.

I'm not just wanting to skip the Down, I want to be unable to reverse the migration. It should remain in the `migrations` table and not be re-run.

**Comment by beenotung** [comment]
A workaround is to introduce error in the down script, e.g. dropping a non-existing table to make the down operation fail.
