### ISSUE TITLE
Hard to fix mistakes in Down migration

### ISSUE THREAD

**Issue by YoshiWalsh** [Kauto/better-sqlite3-helper#11]
For development purposes I'm using `migrate.force: last` to rerun the most recent migration each time I run my application.

If I make a mistake in my `Up` migration, it's rolled back and rerun the next time I run my app, so it's no big deal. But if I make a mistake in my `Down` migration, it's already been stored in the `migrations` table and fixing the mistake requires manually editing my database contents.

I think it would be better if down-migrating used the Down procedure in the migration file on disk, not the one stored in the `migrations` table. This would make it easier to correct mistakes.

**Comment by Kauto** [comment]
You are right. I solved this problem in the new version.
