### ISSUE TITLE
Cannot use on M1/M2 macOS

### ISSUE THREAD

**Issue by paambaati** [Kauto/better-sqlite3-helper#26]
Because of https://github.com/WiseLibs/better-sqlite3/issues/954.

Would you mind bumping the dependency to the latest version?

**Comment by paambaati** [comment]
As a temporary workaround, users on npm 8 or above can modify their `package.json` like this –

```diff
"dependencies": {
   "better-sqlite3-helper": "3.1.6",
+ },
+ {
+ "overrides": {
+  "better-sqlite3": "8.1.0"
+ }
```

**Comment by Kauto** [comment]
sorry for the long wait. I bumped to the newest version.
