### ISSUE TITLE
Cannot open a new database file

### ISSUE THREAD

**Issue by jeniceel1256** [Kauto/better-sqlite3-helper#3]
In order to use it for multiple database files (alpha.db - beta.db) I think you need add a fix to database close

**instance = null;**

```
DB.prototype.close = function () {
  if (this.db) {
    this.db.close()
    this.db = undefined
    instance = null;
  }
  return this
}
```

**Comment by jeniceel1256** [comment]
I have found a workaround in my app by adding the following

```
let options = {...}
DB(options).options = options;
```

**Comment by Kauto** [comment]
You can create more than one instance by using "new". 
const alphaDB = new DB(optionsForAlpha)
const betaDB = new DB(optionsForBeta)

Does this solve your problem?

**Comment by jeniceel1256** [comment]
Yes, it may be possible, but this way is useful if you want to have both databases open at the same time.

**Comment by Kauto** [comment]
Ok, makes sense. I added your suggestion to the code.
