### ISSUE TITLE
Error in electron.js

### ISSUE THREAD

**Issue by isdot** [Kauto/better-sqlite3-helper#4]
`const appRoot = require('app-root-path').path`

The above code not work at `"electron": "^v6.1.7"`

Change to universal code?

**Comment by Kauto** [comment]
since I don't use electron currently, please try my latest commit that removes this dependency.

Keep in mind that this library is based on better-sqlite3. See this thread there how to use it in electron:
https://github.com/JoshuaWise/better-sqlite3/issues/126

**Comment by crossle** [comment]
How about add path as a param ?

**Comment by Kauto** [comment]
You can already do that by using
```
const DB = require('better-sqlite3-helper');

DB({path: yourpath})
```

**Comment by crossle** [comment]
When release the new version?
