### ISSUE TITLE
query is not a function

### ISSUE THREAD

**Issue by onlyLiru** [Kauto/better-sqlite3-helper#8]
DB().query('SELECT * FROM users');

Neither DELETE nor Query methods can be found. Why?

**Comment by Kauto** [comment]
Well, this can have many reasons. F.e. you didn't import better-sqlite3-helper correctly. Or you didn't do a post install. Or you don't have write access on the drive you are working on. Or the table doesn't exist... You should post the error message, so people can help you out.
